### ISSUE TITLE
V1.3 of FT200/FT-RD Product Manual is ready for publishing

### ISSUE THREAD

**Issue by collieking** [BallengerMotorsports/FlagtronicsDocumentation#1]
Can someone publish this newest version of the FT200/FT-RD Product Manual to both Github so it shows up on our Downloads page and to Device Manager. Currently, Device Manage has v0.4 and Github/Downloads Page has v1.1.

[FT200_FT-RD Product Manual v1.2.pdf](https://github.com/user-attachments/files/16933754/FT200_FT-RD.Product.Manual.v1.2.pdf)

```[tasklist]
### Tasks
- [ ] Update and publish V1.2 of Product Manual in Github and Device Manager software. @vtjballeng
- [x] Make link to Product Manual download the PDF versus taking users to Github page. @vtjballeng
```

**Comment by collieking** [comment]
@vtjballeng I'm not sure who has the permissions to do this, but can you have someone update the Product Manual to V1.2 on both Github for our Downloads page but also in Device Manager? Lastly, how can we setup the download link to just download the PDF vs. taking users to the Github page where they have to know where to click to download the PDF?

**Comment by collieking** [comment]
@vtjballeng I’m still waiting for this to get updated to V1.2. Is this something I can do? Seems so simple and I’ve been waiting for 2 weeks. If this is the place to manage issues and tasks, then I need responsiveness please.

**Comment by collieking** [comment]
@vtjballeng I now have Version 1.3 of the Product Manual ready. Here is the link to the Google Doc: https://docs.google.com/document/d/1nKDbwgBSejcmmA_K7PWKKnqmE758yybiSC__X-tFVlk/edit?usp=sharing

I have also attached a PDF Version. Can this be updated today? Both in GitHub and Device Manager? 
[FT200_FT-RD Product Manual v1.3.pdf](https://github.com/user-attachments/files/17117780/FT200_FT-RD.Product.Manual.v1.3.pdf)

- [ ] @vtjballeng Updated Product Manual in GitHub and Device Manager to V1.3

**Comment by vtjballeng** [comment]
@collieking , the website links directly to Github [here ](https://github.com/Flagtronics/Release). The simple process explanation is that you have permissions already for a Pull Request with the update. @mfvmx pushed this through yesterday.

**Comment by collieking** [comment]
@vtjballeng 1) I didn’t have permission to add Morgan to this issue so I sent the issue to him through a link yesterday and he published it. 2) Device Manager still shows V0.4 and no one knows how to update it. Can you explain the process so we can get it done?

**Comment by vtjballeng** [comment]
> @vtjballeng 1) I didn’t have permission to add Morgan to this issue so I sent the issue to him through a link yesterday and he published it. 2) Device Manager still shows V0.4 and no one knows how to update it. Can you explain the process so we can get it done?

1. Yes, you're full empowered to accomplish this. You push the file in the relevant location on release repo and create a PR for it. It gets approved. [Here](https://github.com/Flagtronics/Release/pull/9) @mfvmx did it for you so you can see where the file was pushed. Organizationally, @vtjballeng , & @mfvmx , & @tungree all know how to do this. @AlericS also should but perhaps doesn't. 

2. You update it [here](https://github.com/BallengerMotorsports/Flagtronics-FT200-Software/tree/main/InnoSetup%20Installer/Manual/FT200). Process is the same as #1 above. I added you to the repo with write permission. You push the file, create the PR. It gets merged and makes it into the next release.

**Comment by vtjballeng** [comment]
> @vtjballeng I’m still waiting for this to get updated to V1.2. Is this something I can do? Seems so simple and I’ve been waiting for 2 weeks. If this is the place to manage issues and tasks, then I need responsiveness please.

Yes, you can do it and were empowered to do so. Yes, it is simple once you learn the process.
